### ISSUE TITLE
Repository name must be lowercase

### ISSUE THREAD

**Issue by Wolvverine** [hassio-addons/workflows#50]
Problem:
buildx failed with: ERROR: invalid tag "ghcr.io/Wolvverine/unifi/aarch64:stable": repository name must be lowercase

Resolution:

tags: |
            ghcr.io/${{ github.repository_owner.lowercase }}/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.environment }}
            ghcr.io/${{ github.repository_owner.lowercase }}/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}

https://github.com/marketplace/actions/change-string-case

**Comment by frenck** [comment]
Cool, but not sure what the issue for the community add-ons is in this case?

**Comment by Wolvverine** [comment]
I think it would be worth correcting this in worklogs since it is required as a lowercase. 
Even if in your own repo you give lowercase in the name.

**Comment by frenck** [comment]
Sorry, I'm not following?

These are the workflows for the community add-ons project. Not your personal project.
As written in the readme:

> While these workflows are public, they are subjected to change and not versioned in terms of releases. Using them from this repository directly for other project is possible, but not recommended for that reason.
