### ISSUE TITLE
Question: how to publish release after publishing beta

### ISSUE THREAD

**Issue by hacker-cb** [hassio-addons/workflows#85]
Hello!

I'm using your workflows in my custom repositories.
I made same structure (edge, beta, stable).

Currently I'm publishing to `repository-beta` by creating `pre-release`, it is published ok.

So, my question is how to publish release after that?

Just remove `pre-release` option and re-run deploy workflow manually?

**Comment by frenck** [comment]
> Just remove pre-release option and re-run deploy workflow manually?

Never re-purpose releases>

> So, my question is how to publish release after that?

Tag/create a release 🤷

**Comment by hacker-cb** [comment]
Ok, thanks.
